dtagent:
  container_name: "dtagent"
  hostname: "docker-dtagent"
  image: "pcjeffmac/dynatrace-agent"
  environment:
    DT_AGENT_NAME: "dtagent"
  volumes:
    - /dynatrace
    - "/tmp/log/dynatrace/agents/dtagent:/dynatrace/log/agent"